version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: apirest_is2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  api:
    build: .
    container_name: api-container
    depends_on:
      - db
    environment:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./logs:/root/logs

volumes:
  postgres_data:
