services:
  db:
    image: postgres:15
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
          test: ["CMD-SHELL", "pg_isready -U myuser -d apirest_is2"]
          interval: 5s
          timeout: 5s
          retries: 5
  
  api:
    build: .
    container_name: api-container
    depends_on:
      - db
    restart: always
    environment:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./logs:/root/logs

volumes:
  postgres_data:
